version: "3.8"
services:
  postgres:
    container_name: 'postgres'
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: heslo123
      POSTGRES_DB: postgres
    ports:
      - "61233:5432"
    volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 40s
      retries: 5
      start_period: 60s

  scrapy:
    build: ./scrapers
    depends_on:
      postgres:
        condition: service_healthy
  server:
    build: ./server
    ports:
      - "127.0.0.1:8080:8090"
    depends_on:
      - "scrapy"
    

    

